FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
RUN npm run db:generate

# can you filter down the build down to one app?
RUN npm run build

CMD ["concurrently", "\"npm run start-user-app\"", "\"npm run start-bank-webhook\""]
